services:
  - type: web
    name: streamlit-anomaly-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard/app.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
    autoDeploy: true
